### ISSUE TITLE
和springboot整合后jvppeteer抛出异常导致接口线程全部阻塞

### ISSUE THREAD

**Issue by bestRunner** [fanyong920/jvppeteer#109]
在springboot接口运行一段时间后，因截图过程中出现预期之外的错误导致线程阻塞无法释放
![image](https://user-images.githubusercontent.com/36727232/172369651-a0691150-7c29-4a4d-9343-74db6d90e137.png)

**Comment by bestRunner** [comment]
是否有计划更新这个bug尼？如果失败把线程释放出来尼，否则线程会死掉 @sagexueqi

**Comment by sagexueqi** [comment]
> 是否有计划更新这个bug尼？如果失败把线程释放出来尼，否则线程会死掉 @sagexueqi

后续版本修复，send时如果是block的，也需要支持超时，现在await是一直等待

**Comment by sagexueqi** [comment]
请本地构建`branch_devlop_1.1.6`分支，参考`ConnectionOptionsExample`，配置`sessionWaitingResultTimeout`属性

**Comment by bestRunner** [comment]
![image](https://user-images.githubusercontent.com/36727232/173978512-5155019d-e356-48b5-a559-185007ee2862.png)
当浏览器出现预期之外的错误导致主动关闭，会出现如上异常，请问本次更新是否也一起解决了尼，主要这也会是当前线程死掉。

**Comment by bestRunner** [comment]
> ![image](https://user-images.githubusercontent.com/36727232/173978512-5155019d-e356-48b5-a559-185007ee2862.png)
当浏览器出现预期之外的错误导致主动关闭，会出现如上异常，请问本次更新是否也一起解决了尼，主要这也会是当前线程死掉。

**Comment by bestRunner** [comment]
> 

![image](https://user-images.githubusercontent.com/36727232/173978512-5155019d-e356-48b5-a559-185007ee2862.png)
当浏览器出现预期之外的错误导致主动关闭，会出现如上异常，请问本次更新是否也一起解决了尼，主要这也会是当前线程死掉。

**Comment by kingwudy** [comment]
> 请本地构建`branch_devlop_1.1.6`分支，参考`ConnectionOptionsExample`，配置`sessionWaitingResultTimeout`属性

这个问题我也经常遇到，bugfix为什么不合到master呢？

**Comment by fanyong920** [comment]
浏览器关闭后，websocket的onclose方法接收到回调，将所有等待线程释放

**Comment by fanyong920** [comment]
2.0.0版本后
