### ISSUE TITLE
截图会等待5分钟

### ISSUE THREAD

**Issue by chenruihuang** [fanyong920/jvppeteer#111]
项目构建docker镜像在k8s中运行，进行网页截图时，日志有如下输出，然后会等待5分钟再输出图片，源码中没找到这个输出的地方
截图尺寸为：宽[1280.0]，高[4585.0]
等待5分钟

**Comment by sagexueqi** [comment]
> 项目构建docker镜像在k8s中运行，进行网页截图时，日志有如下输出，然后会等待5分钟再输出图片，源码中没找到这个输出的地方 截图尺寸为：宽[1280.0]，高[4585.0] 等待5分钟

请重新上传截图，谢谢

**Comment by chenruihuang** [comment]
您的邮件我已收到~~~

**Comment by chenruihuang** [comment]
您的邮件我已收到~~~
