### ISSUE TITLE
java 17 环境无法拦截响应

### ISSUE THREAD

**Issue by ztxtxwd** [fanyong920/jvppeteer#118]
jdk: Amazon Corretto 17
示例：`page.onRequest((request) -> {
            System.out.println("页面有请求发出..."+request.url());
        });
        page.onRequestfailed((request) -> {
            System.out.println("页面发出的请求失败了..."+request.url());
        });
        page.onRequestfinished((request) -> {
            System.out.println("页面的请求结束了..."+request.url());
        });
        page.onResponse((response) -> {
            System.out.println("页面请求["+response.url()+"]对应的响应是..."+response.status());
        });`
均未打印

**Comment by fanyong920** [comment]
用最新版本
