### ISSUE TITLE
生成pdf 后控制台输出Connection closed by remote peer Code: 1006 Reason: 

### ISSUE THREAD

**Issue by Felix0830** [fanyong920/jvppeteer#119]
我用示例代码运行生成pdf能正常生成，但是会输出一个连接关闭的提示
![image](https://user-images.githubusercontent.com/8535771/191248078-10de3657-5b82-4e95-9e88-c65e8ff53fdf.png)
我自己写的程序也是一样报这问题
请问各位大佬这是正常的吗

**Comment by RH1999** [comment]
> 我用示例代码运行生成pdf能正常生成，但是会输出一个连接关闭的提示 ![image](https://user-images.githubusercontent.com/8535771/191248078-10de3657-5b82-4e95-9e88-c65e8ff53fdf.png) 我自己写的程序也是一样报这问题 请问各位大佬这是正常的吗

你解决了吗，我也出现这个错误了
