### ISSUE TITLE
Setting the headerTemplate and footerTemplate is not behaving as expected

### ISSUE THREAD

**Issue by msanaulla** [fanyong920/jvppeteer#127]
I tried to set the header and footer template as shown below: 
```
ArrayList<String> arrayList = new ArrayList<>();
LaunchOptions options = new LaunchOptionsBuilder()
        .withArgs(arrayList)
        .withExecutablePath("D:\\chrome-win\\chrome.exe")
        .withHeadless(true).build();
arrayList.add("--no-sandbox");
arrayList.add("--disable-setuid-sandbox");
Browser browser = Puppeteer.launch(options);
Page page = browser.newPage();
page.goTo("https://www.google.co.in");
PDFOptions pdfOptions = new PDFOptions();
pdfOptions.setDisplayHeaderFooter(true);
Margin margin = new Margin();
margin.setTop("2cm");
margin.setLeft("2cm");
margin.setRight("2cm");
margin.setBottom("2cm");
pdfOptions.setMargin(margin);
pdfOptions.setHeaderTemplate("<div class='title'></div>");
pdfOptions.setFooterTemplate("<div class='pageNumber'></div>");
//pdfOptions.setPath("test.pdf");
byte[] pdf = page.pdf(pdfOptions);
Files.write(Path.of("test2.pdf"), pdf);
page.close();
browser.close();
```

But it is not providing the required headers and footers.

**Comment by jackstudiomaster** [comment]
PDFOptions pdfOptions = new PDFOptions();
        if(cn.wingsing.framework.utils.StringUtils.isNotBlank(format)) {
            pdfOptions.setFormat(format);
        }
        pdfOptions.setFooterTemplate("<div \n" +
                "style=\"width:calc(100% - 28px);margin-bottom: -20px; font-size:8px; padding:15px 14px;display: flex;justify-content: flex-end;\">" +
                "<span style=\"width:60px;text-align:center;\">Print Date: </span>" +
                "<span style=\"width:60px;text-align:left;\" class=\"date\"></span>" +
                "<span style=\"width:35px;text-align:center;\" class=\"pageNumber\"></span>" +
                "<span style=\"width:2px;text-align:center;\">/</span>" +
                "<span style=\"width:35px;text-align:center;\" class=\"totalPages\"></span>" +
                "</div>");
        pdfOptions.setDisplayHeaderFooter(true);
        pdfOptions.setPreferCSSPageSize(true);
        Margin margin = new Margin();
        margin.setBottom("30");
        margin.setTop("0");
        margin.setLeft("0");
        margin.setRight("0");
        pdfOptions.setMargin(margin);
        pdfOptions.setPath(pdfPath);


this code can work!!
