### ISSUE TITLE
div 样式background-image base64图 显示不了

### ISSUE THREAD

**Issue by zhangshexin** [fanyong920/jvppeteer#129]
background-image: url(); 显示不了

**Comment by zhangshexin** [comment]
背景样式中的base64图显示不出来

**Comment by boholder** [comment]
```java
PDFOptions pdfOptions = new PDFOptions();
pdfOptions.setPrintBackground(true);
```

https://zhaoqize.github.io/puppeteer-api-zh_CN/#?product=Puppeteer&version=puppeteer-v21.2.0&show=api-pagepdfoptions
