### ISSUE TITLE
鼠标移动步长设置无效

### ISSUE THREAD

**Issue by shicheng-git** [fanyong920/jvppeteer#13]
鼠标移动事件，不管我设置的步长是多少，总是不起作用，直接快速就滑到最后，比如我设置的步长是30或者1000都是一样的，并没有丝毫的停顿。
或许是我没有完全搞懂这个方法，但是网上的Java教程实在是太少了，我用python调用这个方法就是正常的，步长有效，但是Java实现就没有效果，是我哪里做的不对吗？
以下是滑块代码：

//获取滑块按钮
ElementHandle slide = page.$("#nc_1_n1z");

 //获取滑块盒子
 ElementHandle slideBox = page.$("#nc_1__scale_text");

 //鼠标指向滑块中心
pages.mouse().move((int)(slide.boundingBox().getX() + slide.boundingBox().getWidth()/2), (int)(slide.boundingBox().getY() + slide.boundingBox().getHeight()/2));
                   
 //按下鼠标
pages.mouse().down();

Thread.sleep(500);

//移动到最后
pages.mouse().move((int)(slide.boundingBox().getX() + slideBox.boundingBox().getWidth()), (int)(slide.boundingBox().getY() + slide.boundingBox().getHeight()/2), 30);

Thread.sleep(1000);

//松开鼠标
pages.mouse().up();

**Comment by fanyong920** [comment]
把url给我看看

**Comment by fanyong920** [comment]
提交了代码，但是我还没测试。有问题继续留言
