### ISSUE TITLE
有头模式下无法唤起浏览器

### ISSUE THREAD

**Issue by fox-money** [fanyong920/jvppeteer#138]
设置为有头浏览器的时候，本地Mac运行正常，可以掉起浏览器，但是放到Linux服务器上，就会报错；
![image](https://github.com/fanyong920/jvppeteer/assets/47875225/e33c10dd-4256-4ed9-bd51-03f9ec0f30b6)
![image](https://github.com/fanyong920/jvppeteer/assets/47875225/1ab5ba9a-67c1-41d0-8ca5-54fd576fd6d1)

如果我将withHeadless设置为true，Linux不会报错，但是不会掉起浏览器，不知道是哪里设置出了问题

**Comment by ageovb** [comment]
Linux 下在命令行看看能不能启动 chrome

**Comment by fanyong920** [comment]
看提示：nacl helper process running without a sandbox，网上有很多方案，试试
