### ISSUE TITLE
chrome正受到自动测试软件的控制

### ISSUE THREAD

**Issue by xhypeter** [fanyong920/jvppeteer#139]
private static String CHROME_PATH = "D:\\Chrome\\Application\\chrome.exe";
...
ArrayList<String> arrayList = new ArrayList<>();
        LaunchOptions options = new LaunchOptionsBuilder().
                        withArgs(arrayList).
                        withExecutablePath(CHROME_PATH).
                        withHeadless(true).build();
        arrayList.add("--no-sandbox");
        arrayList.add("--disable-setuid-sandbox");
 Browser browser = null;
        try {
            browser = Puppeteer.launch(options);
            Page page = browser.newPage();
            page.goTo("https://www.taobao.com/about/");
            browser.close();
        }catch (Exception e){
            log.error("error ", e);
        }

已经配置好了，为什么每次都提示“chrome正受到自动测试软件的控制” 这个，有没有解决的方法呢

**Comment by xishian** [comment]
com.ruiyun.jvppeteer.core.Constant#DEFAULT_ARGS 里面有个 --enable-automation，看样子得自己改源码了

**Comment by xishian** [comment]
```
LaunchOptions launchOptions = new LaunchOptionsBuilder()
                .withArgs(args)
                .withHeadless(false)
                .withIgnoreDefaultArgs(Collections.singletonList("--enable-automation"))
                .build();
```
从默认的启动参数中过滤掉`--enable-automation`就可以了
