### ISSUE TITLE
url中携带#号的时候会生成不了pdf

### ISSUE THREAD

**Issue by JiavLee** [fanyong920/jvppeteer#147]
使用demo 跑这个baidu.com没有问题
这个地址不行
https://ysotmain.ysclass.net/zhxy/#/redirect/login

**Comment by JiavLee** [comment]
` public static void main(String[] args) throws IOException, ExecutionException, InterruptedException {
        //自动下载，第一次下载后不会再下载
//        BrowserFetcher.downloadIfNotExist(null);
        ArrayList<String> arrayList = new ArrayList<>();
        //生成pdf必须在无头模式下才能生效
        LaunchOptions options = new LaunchOptionsBuilder().withArgs(arrayList).withHeadless(true).build();
        options.setExecutablePath("D:\\workSoftware\\chrome-win\\chrome.exe");
        arrayList.add("--no-sandbox");
        arrayList.add("--disable-setuid-sandbox");
        Browser browser = Puppeteer.launch(options);
        Page page = browser.newPage();
        HashMap<String, String> map = Maps.newHashMap();
        map.put("Authorization","Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJvcGVuQWNjb3VudElkIjoiOTUwNzI2OTI4MTg3NTMxMjY0IiwidGVuYW50SWQiOiI2Nzk3NzczMzk3MjIzMDU1MzYiLCJwbGF0Zm9ybVR5cGUiOiJwYyIsImlkIjoiOTUwNzI2OTI4MzM0MzMxOTA1Iiwib3BlblVzZXJJbmZvSWQiOiI5NTA1MDcwNjYyMjM2Mjk5MjkiLCJ1c2VyTmFtZSI6IjEzNjUwNzA4MzUzIiwiZXhwIjoxNzExMDQ0MDAwLCJvcmdJZCI6IjY3OTY3NTc4MzA3NzMwNDUxNCIsInVzZXJJbmZvSWQiOiI5NTA3MjY5MjgzMzQzMzE5MDQiLCJjcmVhdGVUaW1lc3RhbXAiOiIxNzA4NTAyMzU1MjIyIn0.Fz1Yk4ErfWgnNS2WFrF-FIpZOVKNg3MxGTesu_sLiJs");
        map.put("User-Agent","Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36");
        page.setExtraHTTPHeaders(map);
        page.goTo("https://ysotmain.ysclass.net/zhxy/#/redirect/login");
        PDFOptions pdfOptions = new PDFOptions();
        pdfOptions.setPath("testA2233.pdf");
        page.pdf(pdfOptions);
        page.close();
        browser.close();
    }`

**Comment by fanyong920** [comment]
goto方法设置页面加载到networkidle才算完成。再打印
```java
       Page page = browser.newPage();
        GoToOptions goToOptions = new GoToOptions();
        //这个网页要设置页面加载到NETWORKIDLE状态才能打印，不然打印空白
        goToOptions.setWaitUntil(Collections.singletonList(PuppeteerLifeCycle.NETWORKIDLE));
        page.goTo("https://ysotmain.ysclass.net/zhxy/#/redirect/login",goToOptions);
        PDFOptions pdfOptions = new PDFOptions();
        pdfOptions.setPath("login.pdf");
        pdfOptions.setOutline(true);//生成大纲
        pdfOptions.setPrintBackground(true);//打印背景图形
        pdfOptions.setPreferCSSPageSize(true);
        PDFMargin pdfMargin = new PDFMargin();
        pdfMargin.setTop("1cm");//px,in,cm,mm等单位都可以，会自动转换
        pdfMargin.setBottom("1cm");
        pdfMargin.setLeft("1cm");
        pdfMargin.setRight("1cm");
        pdfOptions.setMargin(pdfMargin);//有页边距才能显示页脚
        pdfOptions.setDisplayHeaderFooter(true);//打印页眉页脚
        page.pdf(pdfOptions);
        //关闭浏览器
        browser.close();
```
