### ISSUE TITLE
自动下载报错

### ISSUE THREAD

**Issue by zwjtfd** [fanyong920/jvppeteer#148]
![image](https://github.com/fanyong920/jvppeteer/assets/62173083/06c12783-a113-4d30-b33e-880ebf8ade11)

**Comment by xvipservice** [comment]
BrowserFetcher.downloadURLs.put("chrome",new HashMap<String, String>() {
            private static final long serialVersionUID = 3441562966233820720L;

            {
                this.put("host", "https://cdn.npmmirror.com/binaries");
                this.put("linux", "%s/chromium-browser-snapshots/Linux_x64/%s/%s.zip");
                this.put("mac", "%s/chromium-browser-snapshots/Mac/%s/%s.zip");
                this.put("win32", "%s/chromium-browser-snapshots/Win/%s/%s.zip");
                this.put("win64", "%s/chromium-browser-snapshots/Win_x64/%s/%s.zip");
            }
        });
        BrowserFetcher.downloadIfNotExist(null);

**Comment by mallocxw** [comment]
可用 ，点赞！
