### ISSUE TITLE
生成pdf的页码是否支持中文

### ISSUE THREAD

**Issue by BingzhangGithub** [fanyong920/jvppeteer#150]
我在使用jvppeteer转换html为pdf时，一下代码生成的页码是阿拉伯数字。
 pdfOptions.setFooterTemplate("<div \n" +
                "style=\"width:calc(100% - 28px);margin-bottom: -20px; font-size:8px; padding:15px 14px;display: flex;justify-content: flex-end;\">" +
                "<span style=\"width:60px;text-align:center;\">Print Date: </span>" +
                "<span style=\"width:60px;text-align:left;\" class=\"date\"></span>" +
                "<span style=\"width:35px;text-align:center;\" class=\"pageNumber\"></span>" +
                "<span style=\"width:2px;text-align:center;\">/</span>" +
                "<span style=\"width:35px;text-align:center;\" class=\"totalPages\"></span>" +
                "</div>");
        pdfOptions.setPreferCSSPageSize(true);
        Margin margin = new Margin();
        margin.setBottom("30");
        margin.setTop("0");
        margin.setLeft("0");
        margin.setRight("0");

问题：是否可以通过调整生成中文的页码和总页数

**Comment by fanyong920** [comment]
java代码无法修改，pdf数据是chrome 传过来的,属于chrome的内部实现
