### ISSUE TITLE
使用chrome浏览区如何调优增加程序处理效率

### ISSUE THREAD

**Issue by jianleiyu** [fanyong920/jvppeteer#157]

**Comment by fanyong920** [comment]
1.不要开多个浏览器，有需要，可以使用多个BrowserContext
2.加载页面有多个阶段，如果只需要加载到domcontentloaded阶段的话，是比较快的，在PuppeteerLifeCycle里面

浏览器都是占很大内存的，增加linux机器性能或许 也是一种解决办法
