### ISSUE TITLE
线程 JvEmitEventThread 和 JvHandleMessageThread CPU占用极高

### ISSUE THREAD

**Issue by xiaomujin** [fanyong920/jvppeteer#163]
版本: 2.2.1
JvEmitEventThread-1 和 JvHandleMessageThread-1 在 centos 上cpu占用极高
![image](https://github.com/user-attachments/assets/bee946f8-e8c4-4243-8629-ca1f1786e080)
![image](https://github.com/user-attachments/assets/3df6de0d-07b0-4c4f-8946-63fbc26bc4ed)

**Comment by fanyong920** [comment]
从2.0.0改了消息处理的方式。
处理消息流程：接收消息-处理消息-处理完毕-接收消息。但是在处理消息的时候，经常会需要向浏览器发送命令然后等待返回，1.x.x版本 处理方式是只发送命令，但不等待。
2.0.0后添加了 JvEmitEventThread 和 JvHandleMessageThread 这两条线程 使得可以实现  发送在处理消息的时候，向浏览器发送命令并等待返回  的效果。
所有从浏览器 通过 Websocket 传回来的消息都由这两条线程处理，并且这两条线程切换频繁，是会导致这样的。

**Comment by fanyong920** [comment]
从2.0.0改了消息处理的方式。
处理消息流程：接收消息-处理消息-处理完毕-接收消息。但是在处理消息的时候，经常会需要向浏览器发送命令然后等待返回，1.x.x版本 处理方式是只发送命令，但不等待。
2.0.0后添加了 JvEmitEventThread 和 JvHandleMessageThread 这两条线程 使得可以实现 在处理消息的时候，向浏览器发送命令并等待返回 的效果。
所有从浏览器 通过 Websocket 传回来的消息都由这两条线程处理，并且这两条线程切换频繁，是会导致这样的。

**Comment by fanyong920** [comment]
再想想，能优化最好啦

**Comment by xiaomujin** [comment]
老师，看看这个 callback，有没有参考价值。
https://github1s.com/MisakaTAT/Shiro/blob/main/src/main/java/com/mikuac/shiro/handler/ActionHandler.java#L73

**Comment by fanyong920** [comment]
这个callback处理逻辑简单一些，单条线程就能处理完成

**Comment by fanyong920** [comment]
试试 2.2.2

**Comment by xiaomujin** [comment]
> 试试 2.2.2

公共仓库里没有拉到包就手动下载了一份，出现了这个错误
![image](https://github.com/user-attachments/assets/3f9bda00-dc12-4f7d-b681-67a3c323d140)
java.lang.ClassNotFoundException: org.java_websocket.drafts.Draft

**Comment by xiaomujin** [comment]
我的是 jdk21

**Comment by fanyong920** [comment]
一会在公共仓库拉下来试试

**Comment by fanyong920** [comment]
或者在release 里下载带依赖的jar包

**Comment by xiaomujin** [comment]
![image](https://github.com/user-attachments/assets/b09ecedc-ef34-48fb-bb92-a953c76a868e)
JvHandleMessageThread 的占用是拉满的

**Comment by xiaomujin** [comment]
![image](https://github.com/user-attachments/assets/cfa287e8-fd9b-46ff-a116-a83f094b1a5e)
空载状态 messagesQueue 是空的 无限循环占用性能了

**Comment by xiaomujin** [comment]
messagesQueue空了以后等待   onMessage来消息以后 再激活

**Comment by xiaomujin** [comment]
> messagesQueue空了以后等待 onMessage来消息以后 再激活

这个怎么样

**Comment by xiaomujin** [comment]
或者单个线程的线程池 往里丢任务

**Comment by fanyong920** [comment]
改了，静待2.2.3

**Comment by xiaomujin** [comment]
解决了
