### ISSUE TITLE
使用chrome版本win64-901912 D_PageGoForwardTest

### ISSUE THREAD

**Issue by besodata** [fanyong920/jvppeteer#172]
[main] INFO com.ruiyun.jvppeteer.core.BrowserRunner - Connect to browser by websocket url: ws://127.0.0.1:29028/devtools/browser/f39932ae-d2cf-4625-9e77-517a9098e349
[WebSocketConnectReadThread-14] INFO com.ruiyun.jvppeteer.transport.WebSocketTransport - Websocket serverHandshake status: WebSocket Protocol Handshake
[JvHandleMessageThread-1] ERROR com.ruiyun.jvppeteer.core.NetworkManager - Unexpected extraInfo events for request 0AFAC22AE6623201D1C827D9309F2737
[JvHandleMessageThread-1] ERROR com.ruiyun.jvppeteer.core.NetworkManager - Unexpected extraInfo events for request 24496.2
[JvHandleMessageThread-1] ERROR com.ruiyun.jvppeteer.core.NetworkManager - Unexpected extraInfo events for request 24496.13
[JvHandleMessageThread-1] ERROR com.ruiyun.jvppeteer.core.NetworkManager - Unexpected extraInfo events for request 24496.14
[JvHandleMessageThread-1] ERROR com.ruiyun.jvppeteer.core.NetworkManager - Unexpected extraInfo events for request 24496.15
[JvHandleMessageThread-1] ERROR com.ruiyun.jvppeteer.core.NetworkManager - Unexpected extraInfo events for request 24496.16
[JvHandleMessageThread-1] ERROR com.ruiyun.jvppeteer.core.NetworkManager - Unexpected extraInfo events for request 24496.17
[JvHandleMessageThread-1] ERROR com.ruiyun.jvppeteer.core.NetworkManager - Unexpected extraInfo events for request 24496.18
[JvHandleMessageThread-1] ERROR com.ruiyun.jvppeteer.core.NetworkManager - Unexpected extraInfo events for request 24496.19
[JvHandleMessageThread-1] ERROR com.ruiyun.jvppeteer.core.NetworkManager - Unexpected extraInfo events for request 24496.21

**Comment by fanyong920** [comment]
之前排查过这个问题，但是还没排查出来，不过影响不大

**Comment by fanyong920** [comment]
与Puppeteer测试过，是同样的结果，没有问题的
