### ISSUE TITLE
delete Cookies异常

### ISSUE THREAD

**Issue by Knight-ZXW** [fanyong920/jvppeteer#175]
com.ruiyun.jvppeteer.exception.ProtocolException: Protocol error (method：Network.deleteCookies): Invalid parameters Failed to deserialize params.partitionKey - BINDINGS: string value expected at position 200\n\tat com.ruiyun.jvppeteer.transport.Callback.waitForResponse(Callback.java:53)\n\tat com.ruiyun.jvppeteer.transport.CallbackRegistry.create(CallbackRegistry.java:33)\n\tat com.ruiyun.jvppeteer.transport.CdpConnection.rawSend(CdpConnection.java:124)\n\tat com.ruiyun.jvppeteer.transport.CdpCDPSession.send(CdpCDPSession.java:87)\n\tat com.ruiyun.jvppeteer.api.core.CDPSession.send(CDPSession.java:25)\n\tat com.ruiyun.jvppeteer.cdp.core.CdpPage.deleteCookie(CdpPage.java:516)\n\tat com.ruiyun.jvppeteer.cdp.core.CdpPage.setCookie(CdpPage.java:549)
![image](https://github.com/user-attachments/assets/28e268f6-ff68-420a-a9f9-6eda887ebb6f)

**Comment by fanyong920** [comment]
给我看看代码，我抽时间修复

**Comment by fanyong920** [comment]
你使用什么版本的jvppeteer和什么版本的chrome呢

**Comment by Knight-ZXW** [comment]
> 你使用什么版本的jvppeteer和什么版本的chrome呢

由于是偶现的问题，我本地是Mac设备没法复现，部署到云 centos 上才会出现。 
用的是centos   Jvppeteer 3.1.1  chrome for tesing  Google Chrome 124.0.6367.118

是不是3.1.1 的jvppeteer 应该用高版本的 chrome

**Comment by fanyong920** [comment]
是的，cookie 的 partitionKey属性 在不同版本的chrome 中不一样，这个属性还挺难处理的

**Comment by fanyong920** [comment]
BrowserContext 也有setcookie了，不过应该也是用高版本chrome

**Comment by fanyong920** [comment]
launchOptions.setDebuggingPort(9222) 后，在浏览器输入localhost:9222/json/protocol ，然后搜索 deleteCookies就发现，低版本没有partitionKey 属性，高版本会有partitionKey。我用131.0.6778.87的chrome  for testing 和 122.0.6208.0的 chrome  for testing看出了不一样

**Comment by Knight-ZXW** [comment]
> setDebuggingPort

🐂🍺，我先升级下版本试试

**Comment by fanyong920** [comment]
不过你不升级也有办法，你自己写一个setcookies，把我的代码复制出来，删除以下部分就行
![image](https://github.com/user-attachments/assets/c5d1083d-3e45-4f4f-ba87-fd42de8dbde5)

**Comment by fanyong920** [comment]
this.primaryTargetClient 可以通过 client（） 获取

**Comment by Knight-ZXW** [comment]
@fanyong920 大佬有遇到过这个问题吗， 我原来用的centos7 ，安装最新版本 会缺少最新的 glibc 及glibc+。 现在换到ubuntu 20后，安装最新的chrome 131 ，无法启动
![image](https://github.com/user-attachments/assets/92b6d455-71a1-4896-ad5a-41d9d8d92eaf)

**Comment by fanyong920** [comment]
在puppeteer库中搜一下错误信息，有相关issue

**Comment by Knight-ZXW** [comment]
> 在puppeteer库中搜一下错误信息，有相关issue


重新安装了dbus 之后 ，之前的错误消失 了但有其他错误
![image](https://github.com/user-attachments/assets/033617d2-abe3-4afe-8806-f98044a59c92)

**Comment by fanyong920** [comment]
websocket连不上，看看服务器内存是否足够，可能是新版本的chrome在服务器上运行缓慢

**Comment by fanyong920** [comment]
#165

**Comment by fanyong920** [comment]
#165 这个issue就是内存不足

**Comment by Knight-ZXW** [comment]
> websocket连不上，看看服务器内存是否足够，可能是新版本的chrome在服务器上运行缓慢

内存充足，目前是32GB的设备

**Comment by Knight-ZXW** [comment]
> launchOptions.setDebuggingPort(9222) 后，在浏览器输入localhost:9222/json/protocol ，然后搜索 deleteCookies就发现，低版本没有partitionKey 属性，高版本会有partitionKey。我用131.0.6778.87的chrome for testing 和 122.0.6208.0的 chrome for testing看出了不一样

目前由于我用的centos 7 ，只能安装 124.0.6367.118版本 ，jvppeteer 库没找到对应的适配版本，现在用的2.2.5 ，功能基本正常，只是一直会有这个序列化失败的日志
![image](https://github.com/user-attachments/assets/3f57008f-ea76-4c42-bf10-058781e1bf9c)

**Comment by fanyong920** [comment]
如果不用request和response相关功能，不影响使用
