### ISSUE TITLE
Browser 能实现  Closeable 吗 

### ISSUE THREAD

**Issue by xiaomujin** [fanyong920/jvppeteer#176]
IOUtils.closeQuietly(browser);

**Comment by xiaomujin** [comment]
org.apache.commons.io 包入参为 Closeable

**Comment by xiaomujin** [comment]
类路径变动太大了 一升就修改 o(TヘTo)

**Comment by fanyong920** [comment]
我记得实现了的

**Comment by fanyong920** [comment]
增加webdriver-bidi协议支持，firefox浏览器支持就改变类路径了吗，bidi现在只支持firefox

**Comment by xiaomujin** [comment]
实现的是 AutoCloseable 
![image](https://github.com/user-attachments/assets/744420eb-47ba-417f-828e-5d1b3e043bf1)

**Comment by fanyong920** [comment]
好的，我回头看看，尽快解决

**Comment by fanyong920** [comment]
不能实现，因为 Closeable是专门给 IO 用的，AutoCloseable用途更加广泛，而浏览器不只是 IO
