### ISSUE TITLE
k8s中 启动浏览器报错

### ISSUE THREAD

**Issue by crazylunsong** [fanyong920/jvppeteer#22]
你好，大佬，请问k8s的docker启动报 error while loading shared libraries: libX11.so.6: cannot open shared object file: No such file or directory 是因为什么呢

**Comment by wxw1111** [comment]
这个问题有什么解决思路吗？

**Comment by crazylunsong** [comment]
> 这个问题有什么解决思路吗?

是因为我的docker环境中少了一些chromium需要的依赖，我在dockerfile中安装了，后面就正常启动了

**Comment by wxw1111** [comment]
> > 这个问题有什么解决思路吗?
> 
> 是因为我的docker环境中少了一些chromium需要的依赖，我在dockerfile中安装了，后面就正常启动了

好的，多谢！已经解决了，可以参考running-puppeteer-in-docker[https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md#running-puppeteer-in-docker]

**Comment by crazylunsong** [comment]
> > > 这个问题有什么解决思路吗?
> > 
> > 
> > 是因为我的docker环境中少了一些chromium需要的依赖，我在dockerfile中安装了，后面就正常启动了
> 
> 好的，多谢！已经解决了，可以参考[running-puppeteer-in-docker](https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md#running-puppeteer-in-docker)

是的 我也是参考的这个文档

**Comment by civetming** [comment]
> > > 这个问题有什么解决思路吗?
> > 
> > 
> > 是因为我的docker环境中少了一些chromium需要的依赖，我在dockerfile中安装了，后面就正常启动了
> 
> 好的，多谢！已经解决了，可以参考[running-puppeteer-in-docker](https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md#running-puppeteer-in-docker)

可以请教一下 是怎么做的吗 我卡在这里了

**Comment by civetming** [comment]
> 已经

可以请教一下 是怎么做的吗 我卡在这里了

**Comment by civetming** [comment]
> 你好，大佬，请问k8s的docker启动报 error while loading shared libraries: libX11.so.6: cannot open shared object file: No such file or directory 是因为什么呢

可以请教一下 是怎么做的吗 我卡在这里了

**Comment by crazylunsong** [comment]
> > 你好，大佬，请问k8s的docker启动报 error while loading shared libraries: libX11.so.6: cannot open shared object file: No such file or directory 是因为什么呢
> 
> 可以请教一下 是怎么做的吗 我卡在这里了

RUN apt-get update -y -q \
    && apt-get install -y -q xvfb libgtk2.0-0 libxtst6 libxss1 libgconf-2-4 libnss3 libasound2 \
    && apt-get install -y libatk-bridge2.0-0 libgtk-3-0 \
    && apt-get install -y fonts-ipafont-gothic fonts-wqy-zenhei fonts-thai-tlwg fonts-kacst fonts-freefont-ttf libxss1 \
          --no-install-recommends
抱歉这么晚回复，这是我当时的做法，你可以参考下

**Comment by lianling121** [comment]
> > > 你好，大佬，请问k8s的docker启动报 error while loading shared libraries: libX11.so.6: cannot open shared object file: No such file or directory 是因为什么呢
> > 
> > 
> > 可以请教一下 是怎么做的吗 我卡在这里了
> 
> RUN apt-get update -y -q && apt-get install -y -q xvfb libgtk2.0-0 libxtst6 libxss1 libgconf-2-4 libnss3 libasound2 && apt-get install -y libatk-bridge2.0-0 libgtk-3-0 && apt-get install -y fonts-ipafont-gothic fonts-wqy-zenhei fonts-thai-tlwg fonts-kacst fonts-freefont-ttf libxss1 --no-install-recommends 抱歉这么晚回复，这是我当时的做法，你可以参考下

我基础镜像是：8-jdk-alpine没有apt-get怎么办呢
