### ISSUE TITLE
page.select()方法选取select标签下指定的option抛出异常

### ISSUE THREAD

**Issue by ObserverYu** [fanyong920/jvppeteer#25]
初步观察源码,发现可能是JSHandle中的evaluate方法没有正确的处理参数

**Comment by fanyong920** [comment]
給個有下拉選項的页面看看




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "fanyong920/jvppeteer"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月13日(星期二) 下午2:45
收件人:&nbsp;"fanyong920/jvppeteer"<jvppeteer@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[fanyong920/jvppeteer] page.select()方法选取select标签下指定的option抛出异常 (#25)





 
初步观察源码,发现可能是JSHandle中的evaluate方法没有正确的处理参数

**Comment by ObserverYu** [comment]
已测试下拉选项,  但是这个方法有没有影响其他地方没有手动测试,  只是看了一下, 好像其他地方没有多参数的情况

**Comment by ObserverYu** [comment]
> 給個有下拉選項的页面看看
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "fanyong920/jvppeteer" <notifications@github.com&gt;; 发送时间:&nbsp;2020年10月13日(星期二) 下午2:45 收件人:&nbsp;"fanyong920/jvppeteer"<jvppeteer@noreply.github.com&gt;; 抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;; 主题:&nbsp;[fanyong920/jvppeteer] page.select()方法选取select标签下指定的option抛出异常 (#25) 初步观察源码,发现可能是JSHandle中的evaluate方法没有正确的处理参数 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

已测试下拉选项, 但是这个方法有没有影响其他地方没有手动测试, 只是看了一下, 好像其他地方没有多参数的情况

**Comment by fanyong920** [comment]
PageSelectExample我修改了一下，使用了page.setContent()
