### ISSUE TITLE
Windows环境下用一个Browser起多个Page后，这些Page不能并行使用吗

### ISSUE THREAD

**Issue by ZhongShangHe** [fanyong920/jvppeteer#30]
在windows环境下，我使用一个Browser.newPage() 创建多个Page后，在多线程中使用这些Page时，发现只会有一个page生效，不能实现并行。
但是当我创建多个Browser时，这些browser是可以并行执行的。
可以在一个browser下面起多个page，然后实现并行执行吗？

**Comment by zero-copy** [comment]
> 在windows环境下，我使用一个Browser.newPage() 创建多个Page后，在多线程中使用这些Page时，发现只会有一个page生效，不能实现并行。 但是当我创建多个Browser时，这些browser是可以并行执行的。 可以在一个browser下面起多个page，然后实现并行执行吗？

不可以，当一个Page激活时，其他Page线程会阻塞。
