### ISSUE TITLE
centos7 下启动报错，麻烦大佬协助下

### ISSUE THREAD

**Issue by Burgges** [fanyong920/jvppeteer#32]
com.ruiyun.jvppeteer.exception.TimeoutException: Timed out after 30000 ms while trying to connect to the browser!Chrome output: /app/.local-browser/linux-722234/chrome-linux/chrome: error while loading shared libraries: libXss.so.1: cannot open shared object file: No such file or directory
	at com.ruiyun.jvppeteer.core.browser.BrowserRunner$StreamReader.getResult(BrowserRunner.java:314)
	at com.ruiyun.jvppeteer.core.browser.BrowserRunner.waitForWSEndpoint(BrowserRunner.java:339)
	at com.ruiyun.jvppeteer.core.browser.BrowserRunner.setUpConnection(BrowserRunner.java:244)
	at com.ruiyun.jvppeteer.launch.ChromeLauncher.launch(ChromeLauncher.java:89)
	at com.ruiyun.jvppeteer.core.Puppeteer.rawLaunch(Puppeteer.java:111)
	at com.ruiyun.jvppeteer.core.Puppeteer.launch(Puppeteer.java:70)

**Comment by Chcoco** [comment]
我也出现了这个问题，临时解决的，不知道对不对
https://www.jianshu.com/p/e464b162d763

**Comment by classcit** [comment]
参考：
https://github-wiki-see.page/m/fanyong920/jvppeteer/wiki/Centos-%E4%B8%8B%E4%BD%BF%E7%94%A8-Jvppeteer

依赖安装（必须）
当出现 error while loading shared libraries:xx.so.0: cannot open shared object file: No such file or directory 错误时，说明缺少依赖，一般来说，执行以下命令可以解决。
yum install pango.x86_64 libXcomposite.x86_64 libXcursor.x86_64 libXdamage.x86_64 libXext.x86_64 libXi.x86_64 libXtst.x86_64 cups-libs.x86_64 libXScrnSaver.x86_64 libXrandr.x86_64 GConf2.x86_64 alsa-lib.x86_64 atk.x86_64 gtk3.x86_64 -y

linux 上截图 或者 PDF 出现乱码时，说明缺少字体，一般来说，执行以下命令可以解决,有可能需要重启。
yum install ipa-gothic-fonts xorg-x11-fonts-100dpi xorg-x11-fonts-75dpi xorg-x11-utils xorg-x11-fonts-cyrillic xorg-x11-fonts-Type1 xorg-x11-fonts-misc -y

**Comment by mobzheng** [comment]
大佬解决了吗，我也遇到了

**Comment by changkeke** [comment]
解决了。就是缺少一些依赖。我当时整理了，你可以参考下我这篇文章：linux上，使用 jvppeteer 启动chrome报错：缺少 libXss.so.1 - 简书 (jianshu.com)




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "fanyong920/jvppeteer"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月8日(星期四) 下午5:52
***@***.***&gt;;
抄送:&nbsp;"Bounty ***@***.******@***.***&gt;;
主题:&nbsp;Re: [fanyong920/jvppeteer] centos7 下启动报错，麻烦大佬协助下 (#32)





 
大佬解决了吗，我也遇到了

**Comment by changkeke** [comment]
> 大佬解决了吗，我也遇到了

https://www.jianshu.com/p/e464b162d763

**Comment by mobzheng** [comment]
谢谢大佬，我最后是直接在centos中启动了，成功导出pdf了。我想试试在docker里面，大佬有实践过吗
