### ISSUE TITLE
导出pdf时设置setViewport的高宽没有效果

### ISSUE THREAD

**Issue by cugbird** [fanyong920/jvppeteer#33]
为page设置height和width之后，导出的pdf还是使用的默认的600.800的宽高

**Comment by fanyong920** [comment]
具体代码要看看才行

**Comment by cugbird** [comment]
> 具体代码要看看才行

好吧，我自己的问题，在设置page的viewport之后，导出pdf时还有一个设置，需要与viewport的height和width保持一致，这样生成的pdf才是最优的。
我忘了设置pdf的option
