### ISSUE TITLE
有没有使用过coverage来拦截样式和js文件请求的？node下是这样用的，Java下面的代码会出现timeout.数据也获取不到

### ISSUE THREAD

**Issue by zhangcyuan** [fanyong920/jvppeteer#35]
Page page = browser.newPage();
        page.coverage().startCSSCoverage(true);
        page.coverage().startJSCoverage(true,false);
        page.goTo("https://www.baidu.com/");
        List<CoverageEntry> list1 = page.coverage().stopCSSCoverage();
        List<CoverageEntry> list2 = page.coverage().stopJSCoverage();

**Comment by fanyong920** [comment]
确实是代码的问题，我修改了一下，现在暂时可以跑通了

**Comment by fanyong920** [comment]
请看 CoverageExample
