### ISSUE TITLE
header referer setting is not valid

### ISSUE THREAD

**Issue by hehujun** [fanyong920/jvppeteer#37]
header referer setting is not valid
code example:
Map<String, String> headers = new HashMap<>();
...
page.setExtraHTTPHeaders(headers);

or

PageNavigateOptions pageNavigateOptions = new PageNavigateOptions();
pageNavigateOptions.setReferer("......");
page.goTo(url, pageNavigateOptions);

Both do  not work

**Comment by fanyong920** [comment]
发送参数 referer 改成 referrer
