### ISSUE TITLE
Navigation timeout of 30000 ms

### ISSUE THREAD

**Issue by thunder-jump** [fanyong920/jvppeteer#38]
linux上安装google chrome后，使用jvppeteer转pdf时候会Navigation timeout of 30000 ms，本地上ok，不知这个问题要怎么解决
Connect to browser by websocket url: ws://127.0.0.1:34029/devtools/browser/30b0c8fb-9c15-44f1-abfc-ae4fd6e37434，Navigation timeout of 30000 ms exceeded at

**Comment by lgtGitHub** [comment]
老哥 一样的问题，你解决了吗？

**Comment by fanyong920** [comment]
no-sanbox 参数，添加上
