### ISSUE TITLE
调用page.emulate() 会报超时错误 com.ruiyun.jvppeteer.exception.TimeoutException: Navigation timeout of 30000 ms exceeded

### ISSUE THREAD

**Issue by Lansoon** [fanyong920/jvppeteer#4]
无法调用page.emulate模拟手机，会报一个超时错误
 com.ruiyun.jvppeteer.exception.TimeoutException: Navigation timeout of 30000 ms exceeded
` public void setViewport(Viewport viewport) {
        boolean needsReload = this.emulationManager.emulateViewport(viewport);
        this.viewport = viewport;
        if (needsReload)
            this.reload(null);
    }`
应该是在reload的时候导致的。

**Comment by fanyong920** [comment]
是的。导致这个问题的原因是：
在Page.reload()方法中，我应该先发送Page.reload，再等待结果。
![image](https://user-images.githubusercontent.com/45630410/82794645-65a00600-9ea5-11ea-862c-88123ce36933.png)
现在已经更正过来，重新测试一下
