### ISSUE TITLE
内存占用问题

### ISSUE THREAD

**Issue by itzuimao** [fanyong920/jvppeteer#47]
在做并发爬虫任务时（不停的开启新的chrome进程），偶尔会有调用close方法关不掉的浏览器，可以通过批处理杀死chrome进程，但是Java程序的内存占用会越来越高，使用jmap查询是[B和[C占用最高
![image](https://user-images.githubusercontent.com/24363953/105008289-00bca000-5a74-11eb-975f-f799e4999816.png)

请问这个情况如何处理？

**Comment by fedkey** [comment]
用线程池启动线程，再做个定时器，杀掉那些达到设定时间因异常不能关掉的窗口

**Comment by fanyong920** [comment]
现在都采用 pid kill的方式杀死 chrome
