### ISSUE TITLE
你好，在vue中如何使用Puppeteer

### ISSUE THREAD

**Issue by wasd345** [fanyong920/jvppeteer#49]
你好，在vue中如何使用Puppeteer，有人知道吗

**Comment by MaxBill** [comment]
Puppeteer 和 vue没啥关系呀，你可以具体描述下

**Comment by hanbing5210** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
