### ISSUE TITLE
Calling Network.setBlockedURLs

### ISSUE THREAD

**Issue by mahdix** [fanyong920/jvppeteer#52]
Hi,

Do you know if there is a way to call "Network.setBlockedURLs" using this library?

**Comment by fanyong920** [comment]
I try,but not success
Might be a bug in CDP itself e.g. [crbug.com/961676](url) says blocking doesn't work in devtools

**Comment by fanyong920** [comment]
`Page page = browser.newPage();
        page.goTo("http://www.baidu.com");
        CDPSession cdpSession = page.target().createCDPSession();
        HashMap params = new HashMap();
        List urls = new ArrayList();
        urls.add("*.gif");
        params.put("urls", urls);
        cdpSession.send("Network.setBlockedURLs",params,true);
        page.goTo("http://www.baidu.com");`

**Comment by mahdix** [comment]
Thanks @fanyong920 . Looks like Page itself has an instance of CDPSession. Can't we use that one? instead of creating a new session?

**Comment by fanyong920** [comment]
I also try it ,same not success
download code and modify it
Class Page#client() .  make it public
```java
public CDPSession client() {
        return client;
    }
```
```java
       CDPSession cdpSession = page.client();
        HashMap params = new HashMap();
        List urls = new ArrayList();
        urls.add("*.gif");
        params.put("urls", urls);
        cdpSession.send("Network.setBlockedURLs",params,true);
        page.goTo("http://www.baidu.com");
```

**Comment by liuhulu** [comment]
> 成功！
> 
> 下载代码并对其进行修改
> Class Page＃client（）。公开
> 
> ```java
> public  CDPSession client（）{
>         返回客户端；
>     }
> ```
> 
> ```java
>        LaunchOptions options = 新的 LaunchOptionsBuilder（）。withArgs（arrayList）。withHeadless（false）。withDevtools（true）。建造（）;
>         arrayList 。add（“ --no-sandbox ”）;
>         arrayList 。add（“ --disable-setuid-sandbox ”）;
>         浏览器browser =  Puppeteer 。启动（选项）；
>         页面page =浏览器。新一页（）;
>         CDPSession cdpSession =页面。客户（）;
>         HashMap params =  new  HashMap（）;
>         列表网址= 新的 ArrayList（）;
>         网址。add（“ * .gif ”）;
>         参数。put（“ urls ”，urls）;
>         cdpSession 。send（“ Network.setBlockedURLs ”，params，true）;
>         页面。goTo（“ http://www.baidu.com ”）;
> ```
> 
> 在devtool工具栏，点击网络，可以看到所有的gif都是红色的



> success！
> 
> download code and modify it
> Class Page#client() . make it public
> 
> ```java
> public CDPSession client() {
>         return client;
>     }
> ```
> 
> ```java
>        LaunchOptions options = new LaunchOptionsBuilder().withArgs(arrayList).withHeadless(false).withDevtools(true).build();
>         arrayList.add("--no-sandbox");
>         arrayList.add("--disable-setuid-sandbox");
>         Browser browser = Puppeteer.launch(options);
>         Page page = browser.newPage();
>         CDPSession cdpSession = page.client();
>         HashMap params = new HashMap();
>         List urls = new ArrayList();
>         urls.add("*.gif");
>         params.put("urls", urls);
>         cdpSession.send("Network.setBlockedURLs",params,true);
>         page.goTo("http://www.baidu.com");
> ```
> 
> devtool toolbar, click Network,can see all gif are red

可以把这个方法直接暴漏出去么。Page#client() 。目前是protected的

**Comment by fanyong920** [comment]
可以
