### ISSUE TITLE
你好，我想了解下如何使用jvppeteer获取页面的WebSocket请求

### ISSUE THREAD

**Issue by lim-wei** [fanyong920/jvppeteer#54]
我在ko控制浏览器的过程中，希望获取到webSocker请求来查看一些信息
![image](https://user-images.githubusercontent.com/40015199/109108538-b9aa8480-776e-11eb-9234-ca57de326f66.png)
我在Puppeteer 中找到了相关的文章
![image](https://user-images.githubusercontent.com/40015199/109108399-751ee900-776e-11eb-9168-75305993f382.png)
但是在CDPSession.send('Network.enable')发现还需要填入params参数，我对webSocket不是很了解，想请问一下这里需要怎么做

**Comment by anyflywen** [comment]
可以传入null
