### ISSUE TITLE
无头模式和有头模式，浏览器检测不通过。

### ISSUE THREAD

**Issue by liuhulu** [fanyong920/jvppeteer#56]
有头的测试报告。👇
![有头](https://user-images.githubusercontent.com/12758016/109174933-43cf0900-77c0-11eb-81b9-494b8d29399e.png)

无头的测试报告。 👇
![无头](https://user-images.githubusercontent.com/12758016/109174964-4df10780-77c0-11eb-871d-28fa06ce4035.png)

验证地址：https://bot.sannysoft.com/

无头模式下，这些红色的验证，应该如何伪装？

**Comment by liuhulu** [comment]
fyi,https://www.npmjs.com/package/puppeteer-extra-plugin-stealth

**Comment by zero-copy** [comment]
> 仅供参考，[HTTPS：](https://www.npmjs.com/package/puppeteer-extra-plugin-stealth) //www.npmjs.com/package/puppeteer-extra-plugin-stealth[](https://www.npmjs.com/package/puppeteer-extra-plugin-stealth)

如何加入？

**Comment by hks2002** [comment]
在 Chrome 启动时加上 --ignore-certificate-errors 和 --ignore-urlfetcher-cert-requests 参数来解决该问题。

**Comment by fanyong920** [comment]
阅读[puppeteer-extra-plugin-stealth](https://www.npmjs.com/package/puppeteer-extra-plugin-stealth)源码，自己添加
