### ISSUE TITLE
非无头模式必须保持浏览器在最前面

### ISSUE THREAD

**Issue by gaoxiaobo0513** [fanyong920/jvppeteer#57]
有头模式下，必须保持浏览器在最前面（前台），否则不操作。

多线程操作多个浏览器的情况下，会出现切来切去的情况，这种有办法解决吗？

无头模式不存在上述情况。

**Comment by eacdy** [comment]
相同的问题，请问怎解决的啊

**Comment by fanyong920** [comment]
bingtoFont确保在最前面
