### ISSUE TITLE
--enable-automation 不起作用，

### ISSUE THREAD

**Issue by fedkey** [fanyong920/jvppeteer#6]
# #首先谢谢你提供这么好的工具，有个地方不是很明白，打算用这个库开发一个爬虫，但是这个： navigator.webdriver 为true， 即使使用了：--enable-automation也不起作用。能不能帮忙看看，要怎么设置才行。

    public static void main(String[] args) throws IOException, InterruptedException, ExecutionException {

        Puppeteer puppeteer = new Puppeteer();
        //创建下载实例
        BrowserFetcher browserFetcher = puppeteer.createBrowserFetcher();
        //下载最新版本的chromuim
        ArrayList<String> argList = new ArrayList<>();
        argList.add("--no-sandbox");
        argList.add("--disable-setuid-sandbox");
        argList.add("--enable-automation");
        argList.add("--disable-infobars");
        argList.add("--disable-dev-shm-usage");
        LaunchOptions options = new LaunchOptionsBuilder()
                .withDumpio(true).withIgnoreHTTPSErrors(true)
                .withArgs(argList).withHeadless(false)
                .build();
        browserFetcher.download("656675");
        Browser browser = Puppeteer.launch(options);
        Page page = browser.newPage();
        page.goTo("https://www.baidu.com");
        String version = browser.version();
        System.out.println(version);
        Thread.sleep(50000);
        browser.close();
    }

感谢

**Comment by fedkey** [comment]
已经解决了，添加 .withIgnoreAllDefaultArgs(true) 启动项就可以了。并去除 --enable-automation项，这和nodejs有点不同。

**Comment by fanyong920** [comment]
因为两种语言的语法不太一样，所以就将这个参数拆分了两个参数。

**Comment by fanyong920** [comment]
我感觉可以改进一下，我会研究一下如何改进。

**Comment by netsafer** [comment]
> 已经解决了，添加 .withIgnoreAllDefaultArgs(true) 启动项就可以了。并去除 --enable-automation项，这和nodejs有点不同。

神奇，我这边这样设置了，还是 window.navigator.webdriver=true
