### ISSUE TITLE
request.respond() 方法，heards值如果name重复有问题

### ISSUE THREAD

**Issue by Owen0527** [fanyong920/jvppeteer#64]
public JsonNode respond(int status, Map<String, String> headers, String contentType, String body) 
方法，当响应的cookie 有多个的时候无法传值，只设置到一个，这里不应该用map传header，而应该是数组

**Comment by anyflywen** [comment]
在我的仓库dev分支写了支持你要求的respond方法

**Comment by fanyong920** [comment]
已修复
