### ISSUE TITLE
Echarts图形绘制,page.setContent( )方法无法引入本地的js文件

### ISSUE THREAD

**Issue by a908236075** [fanyong920/jvppeteer#66]
`Page page = browser.newPage();

> String echartsJsPath="echarts.min.js";

> //  String echartsJsPath="https://cdn.staticfile.org/echarts/4.3.0/echarts.min.js";

> page.setContent("<html>\n" +
                   "<head>\n" +
                    "    <meta charset=\"utf-8\">\n" +
                    "    <title>第一个 ECharts 实例</title>\n" +
                    "    \n" +
                    "    <script src=\""+echartsJsPath+"\"></script>\n" +
                    "</head>" +
                    "</html>");`

> 我想在springboot项目中生成一个echarts图形,当有网的时候,**引入网址的echarts图形能正常的显示.我想引入本地echarts.js**,可是我尝试了所有的位置,例如classpath下面添加echarts.min.js,或者代码的同级目录下,甚至是浏览器的压缩包以及周围,还尝试了用绝对路径进行引入,都没有引入成功,谁知道正确的引入方式是什么样的?

**Comment by a908236075** [comment]
好几天了 竟然没人回答.....

**Comment by fanyong920** [comment]
可以通过addscript引入
