### ISSUE TITLE
如何设置chrome浏览器中下载文件的路径

### ISSUE THREAD

**Issue by fendo8888** [fanyong920/jvppeteer#68]
如何设置chrome下载文件的路径？

**Comment by fendo8888** [comment]
看文档：https://chromedevtools.github.io/devtools-protocol/tot/Browser/#method-setDownloadBehavior 好像可以设置，但是，该方法好像没有封装

**Comment by fendo8888** [comment]
以下方式可以：
`   Map<String, Object> params = new HashMap<>();
        params.put("behavior", "allow");
        params.put("downloadPath", "D:\\xxxx\\");
        JsonNode send = page.target().createCDPSession().send("Page.setDownloadBehavior", params, true);`

**Comment by fanyong920** [comment]
现在已经封装了，v 2.2.2
