### ISSUE TITLE
新增功能

### ISSUE THREAD

**Issue by anyflywen** [fanyong920/jvppeteer#71]
可以任意模拟请求
可以任意获取Page上的图片（你懂的，当有图片验证码的时候）
可以任意获取network出现的响应内容（你懂的，当response.text报No resource with given identifier found时）
可以不用关闭Browse任意切换代理
修复若干Bug
优化部分监听和性能
降低部分反爬机率

**Comment by 844704781** [comment]
如何在不关闭browser的情况下切换代理

**Comment by fanyong920** [comment]
good
