### ISSUE TITLE
jveppeteer 能加载puppeteer-extra-plugin-stealth吗  如何加载的呢

### ISSUE THREAD

**Issue by 815074104** [fanyong920/jvppeteer#73]
![image](https://user-images.githubusercontent.com/82294775/132683620-c838534b-57ac-427b-87aa-76366e27907d.png)
我尝试了java中使用的selenium加载stealth.min.js的方法 不可用 google还是直接识别了。

**Comment by 815074104** [comment]
nodejs 是完全可用的。于是想尝试一下java版的puppeteer
![image](https://user-images.githubusercontent.com/82294775/132684483-c7bd8f73-195a-49f9-8911-5b5bed47695b.png)

**Comment by zero-copy** [comment]
> nodejs 是完全可用的。于是想尝试一下java版的puppeteer ![image](https://user-images.githubusercontent.com/82294775/132684483-c7bd8f73-195a-49f9-8911-5b5bed47695b.png)

请问你的问题解决了吗，可以支持puppeteer-extra-plugin-stealth吗？

**Comment by 815074104** [comment]
没解决。还不能用。

**Comment by xing115601zxc** [comment]
`page.evaluateOnNewDocument(js, PageEvaluateType.STRING, new Object[]{});`
我是這樣串上的，參考看看
