### ISSUE TITLE
headless为true情况下，设置navigationtimeout为0，还是报30s超时

### ISSUE THREAD

**Issue by amg168** [fanyong920/jvppeteer#81]
headless设置TRUE时，设置navigationtimeout为0，还是报30s超时，但是设置为false时，都能正常解析，请教下这是为啥？

**Comment by addisondnf** [comment]
PageNavigateOptions navigateOptions = new PageNavigateOptions();
navigateOptions.setTimeout(TIME_OUT); // 设置60000 60s超时
navigateOptions.setWaitUntil(Arrays.asList(
	"load",                  //等待 “load” 事件触发
	"domcontentloaded",      //等待 “domcontentloaded” 事件触发
	"networkidle0",          //在 500ms 内没有任何网络连接
	"networkidle2"           //在 500ms 内网络连接个数不超过 2 个
));

Boolean ok = page.goTo(url,navigateOptions).ok();

设置久一点的超时时间，我这边可以避免抛出这个异常，可以正常生成PDF文件信息。page.goto方法多穿一个参数：navigateOptions  即可
