### ISSUE TITLE
MAC 下调用demo 错误，WebSocketTransport - Websocket error: java.lang.NullPointerException: null

### ISSUE THREAD

**Issue by zeroxiao** [fanyong920/jvppeteer#82]
mac pro 2019  I7
jdk 8
调用所有的demo 都报以下错误

22:47:12.304 [main] INFO com.ruiyun.jvppeteer.core.browser.BrowserFetcher - revision:722234，executablePath:/Users/0012/workspace/java/renrong-yuqing/.local-browser/mac-722234/chrome-mac/Chromium.app/Contents/MacOS/Chromium，folderPath:/Users/0012/workspace/java/renrong-yuqing/.local-browser/mac-722234，local:true，url:https://npm.taobao.org/mirrors/chromium-browser-snapshots/Mac/722234/chrome-mac.zip，product:chrome
22:47:12.620 [main] INFO com.ruiyun.jvppeteer.core.browser.BrowserFetcher - revision:722234，executablePath:/Users/0012/workspace/java/renrong-yuqing/.local-browser/mac-722234/chrome-mac/Chromium.app/Contents/MacOS/Chromium，folderPath:/Users/0012/workspace/java/renrong-yuqing/.local-browser/mac-722234，local:true，url:https://npm.taobao.org/mirrors/chromium-browser-snapshots/Mac/722234/chrome-mac.zip，product:chrome
22:47:12.965 [WebSocketConnectReadThread-16] INFO com.ruiyun.jvppeteer.transport.WebSocketTransport - Connection closed by remote peer Code: -1 Reason: 
22:47:12.968 [WebSocketConnectReadThread-16] ERROR com.ruiyun.jvppeteer.transport.WebSocketTransport - Websocket error:
java.lang.NullPointerException: null
	at com.ruiyun.jvppeteer.transport.WebSocketTransport.onClose(WebSocketTransport.java:61)
	at org.java_websocket.client.WebSocketClient.onWebsocketClose(WebSocketClient.java:617)
	at org.java_websocket.WebSocketImpl.closeConnection(WebSocketImpl.java:522)
	at org.java_websocket.WebSocketImpl.closeConnection(WebSocketImpl.java:534)
	at org.java_websocket.WebSocketImpl.eot(WebSocketImpl.java:572)
	at org.java_websocket.client.WebSocketClient.run(WebSocketClient.java:510)
	at java.lang.Thread.run(Thread.java:748)

**Comment by fanyong920** [comment]
launchOptions.excuablePath("")

**Comment by olderwang** [comment]
请问，这个有处理结果吗？我也碰到这个问题了。

**Comment by fanyong920** [comment]
Mac必须用withExcutablePath是用來指定启动Chrome.exe的路径。Mac解压chrome.zip有问题

**Comment by HappyArthorn** [comment]
@fanyong920  你好，这个错误我在linux生产环境也遇到了，而且在开发、测试的linux环境都没问题。
具体现象就是java服务刚启动进行下载是可以的，但是过一段时间就会出现这个问题。
具体代码如下：

**Comment by nuistchh** [comment]
download clumsy-0.3-win64-a.zip  

reproduce steps

1.unzip clumsy-0.3-win64-a.zip 

2.search ws port in  log file 

![image-2023-12-13-09-19-30-001](https://github.com/fanyong920/jvppeteer/assets/6769284/d0b07454-bbf0-4a6a-9083-751108237877)

3. open cmd run "netstat -ano|findstr 54667"  // ${ws port} find the client&server port 54668 54667
![image-2023-12-13-09-27-54-169](https://github.com/fanyong920/jvppeteer/assets/6769284/edf13da5-089a-430c-8b82-40af59cbfbc0)


4 run clumsy  drop all the package from 54668 54667,then click start

![image-2023-12-13-09-29-49-930](https://github.com/fanyong920/jvppeteer/assets/6769284/85a086b9-6e14-49cc-9998-5b13c9ce6306)


5.  now the issue can reproduce

How to fix
com.ruiyun.jvppeteer.transport.WebSocketTransport

before:
public void onClose( int code, String reason, boolean remote ) {
		LOGGER.info("Connection closed by " + ( remote ? "remote peer" : "us" ) + " Code: " + code + " Reason: " + reason );
		// The codecodes are documented in class org.java_websocket.framing.CloseFrame
		this.onClose();
		this.connection.dispose();
	}

after:
private static final ExecutorService cachedThreadPool = Executors.newCachedThreadPool();
 public void onClose( int code, String reason, boolean remote ) {
            WebSocketTransport thiz = this;
            cachedThreadPool.execute(new Runnable() {
                @Override
                public void run() {
                    try {
                        //重连间隔十秒
                        Thread.sleep(10000);
                    } catch (InterruptedException e) {
                        e.printStackTrace();
                    }
                    try {
                        thiz.reconnectBlocking();
                        try{
                            Map<String, Object> params = new HashMap<>();
                            params.put("discover", true);
                            connection.send("Target.setDiscoverTargets", params, false);
                            LOGGER.warn("reconnect succ");
                        }catch (Exception e){
                            LOGGER.warn("send Target.setDiscoverTargets error");
                        }
                    } catch (InterruptedException e) {
                        LOGGER.warn("reconnecting fail");
                    }
                    LOGGER.warn("reconnecting");
                }
            });
        
    }
