### ISSUE TITLE
Connection closed by remote peer Code: -1 Reason: 

### ISSUE THREAD

**Issue by olderwang** [fanyong920/jvppeteer#85]
系统版本：CentOS Linux release 7.9.2009 (Core)
jyppeteer版本：1.1.3
代码demo
![image](https://user-images.githubusercontent.com/29946712/144556824-362faadc-f0c1-421d-8a66-90ca57b3318f.png)

运行报错截图
![image](https://user-images.githubusercontent.com/29946712/144545500-bbc04955-4c4a-4ae9-b1dd-e6bc628bff77.png)

**Comment by fanyong920** [comment]
withExcutablePath是用來指定启动Chrome.exe的路径。，截图中是 “” 是不可以的

**Comment by olderwang** [comment]
去掉这个也不行的。
![image](https://user-images.githubusercontent.com/29946712/144774465-07cdbbea-e95e-447b-9418-2d98e214cea6.png)![image](https://user-images.githubusercontent.com/29946712/144774442-3cdf091f-f1d1-48f2-b18f-c14e3d8bf6b8.png)![Uploading image.png…]()

**Comment by olderwang** [comment]
经过测试发现是系统环境问题，换了台机器就好了。
