### ISSUE TITLE
page setUserAgent 能否改成公共方法，现在改变只能设置device

### ISSUE THREAD

**Issue by Owen0527** [fanyong920/jvppeteer#9]
/**
     * 给页面设置userAgent
     *
     * @param userAgent userAgent的值
     */
    private void setUserAgent(String userAgent) {
        this.frameManager.networkManager().setUserAgent(userAgent);
    }

**Comment by fanyong920** [comment]
对的，应该这么做。已提交

**Comment by fanyong920** [comment]
对的，应该这么做。已提交
