### ISSUE TITLE
JDK8+，在对请求进行拦截处理的时候（Request.respond）， 会因为编码问题报错（Base64.getDecoder().decode(responseBody)）

### ISSUE THREAD

**Issue by jiayunwu** [fanyong920/jvppeteer#91]
问题描述： 如题， 设置 body的时候， 会有编码错误
原因： jdk7中，Base64编码包含换行，而在jdk8中，不包含换行，解码就会出错。
建议： 使用apache common包中的org.apache.commons.codec.binary.Base64类进行编码和解码；

**Comment by sagexueqi** [comment]
后续版本修复
